# Generated by Django 2.1.3 on 2018-12-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 12, 22, 19, 48, 32, 900617), verbose_name='Опубликована'),
        ),
    ]
