# Generated by Django 2.1.3 on 2018-12-22 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181222_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 12, 22, 20, 35, 30, 691400), verbose_name='Опубликована'),
        ),
    ]
