# Generated by Django 2.1.3 on 2018-12-22 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181222_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 12, 22, 22, 16, 38, 741999), verbose_name='Опубликована'),
        ),
    ]
