# Generated by Django 2.1.3 on 2018-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_blogarticle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
